services:
  sonar:
    image: sonarqube:latest
    env_file:
      - .env
    container_name: sonar
    ports:
      - 9000:9000
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar-logs:/opt/sonarqube/logs
      - sonar-conf:/opt/sonarqube/conf
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
  redis-data:
  sonar-data:
  sonar-extensions:
  sonar-logs:
  sonar-conf: